// Code generated by "stringer -type=ComparisonOp"; DO NOT EDIT.

package filter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Eq-0]
	_ = x[Ne-1]
	_ = x[In-2]
	_ = x[Out-3]
	_ = x[Lt-4]
	_ = x[Le-5]
	_ = x[Gt-6]
	_ = x[Ge-7]
}

const _ComparisonOp_name = "EqNeInOutLtLeGtGe"

var _ComparisonOp_index = [...]uint8{0, 2, 4, 6, 9, 11, 13, 15, 17}

func (i ComparisonOp) String() string {
	if i < 0 || i >= ComparisonOp(len(_ComparisonOp_index)-1) {
		return "ComparisonOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComparisonOp_name[_ComparisonOp_index[i]:_ComparisonOp_index[i+1]]
}
