// Code generated by "stringer -type=LogicalOp"; DO NOT EDIT.

package filter

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[And-0]
	_ = x[Or-1]
}

const _LogicalOp_name = "AndOr"

var _LogicalOp_index = [...]uint8{0, 3, 5}

func (i LogicalOp) String() string {
	if i < 0 || i >= LogicalOp(len(_LogicalOp_index)-1) {
		return "LogicalOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogicalOp_name[_LogicalOp_index[i]:_LogicalOp_index[i+1]]
}
