// Code generated by "stringer -type=BoolOp"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[And-0]
	_ = x[Or-1]
}

const _BoolOp_name = "AndOr"

var _BoolOp_index = [...]uint8{0, 3, 5}

func (i BoolOp) String() string {
	if i < 0 || i >= BoolOp(len(_BoolOp_index)-1) {
		return "BoolOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BoolOp_name[_BoolOp_index[i]:_BoolOp_index[i+1]]
}
