// Code generated by "stringer -type=CompOp"; DO NOT EDIT.

package ast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Eq-0]
	_ = x[Ne-1]
	_ = x[In-2]
	_ = x[Out-3]
	_ = x[Lt-4]
	_ = x[Le-5]
	_ = x[Gt-6]
	_ = x[Ge-7]
}

const _CompOp_name = "EqNeInOutLtLeGtGe"

var _CompOp_index = [...]uint8{0, 2, 4, 6, 9, 11, 13, 15, 17}

func (i CompOp) String() string {
	if i < 0 || i >= CompOp(len(_CompOp_index)-1) {
		return "CompOp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompOp_name[_CompOp_index[i]:_CompOp_index[i+1]]
}
