// Code generated by "stringer -type=tokenType -trimprefix=tok"; DO NOT EDIT.

package rsql

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokIdent-2]
	_ = x[tokString-4]
	_ = x[tokInteger-8]
	_ = x[tokFloat-16]
	_ = x[tokFalse-32]
	_ = x[tokTrue-64]
	_ = x[tokNull-128]
	_ = x[tokEq-256]
	_ = x[tokNe-512]
	_ = x[tokIn-1024]
	_ = x[tokOut-2048]
	_ = x[tokLt-4096]
	_ = x[tokLe-8192]
	_ = x[tokGt-16384]
	_ = x[tokGe-32768]
	_ = x[tokAnd-65536]
	_ = x[tokOr-131072]
	_ = x[tokLparen-262144]
	_ = x[tokRparen-524288]
	_ = x[tokInvalid-1048576]
	_ = x[tokEOF-2097152]
}

const _tokenType_name = "IdentStringIntegerFloatFalseTrueNullEqNeInOutLtLeGtGeAndOrLparenRparenInvalidEOF"

var _tokenType_map = map[tokenType]string{
	2:       _tokenType_name[0:5],
	4:       _tokenType_name[5:11],
	8:       _tokenType_name[11:18],
	16:      _tokenType_name[18:23],
	32:      _tokenType_name[23:28],
	64:      _tokenType_name[28:32],
	128:     _tokenType_name[32:36],
	256:     _tokenType_name[36:38],
	512:     _tokenType_name[38:40],
	1024:    _tokenType_name[40:42],
	2048:    _tokenType_name[42:45],
	4096:    _tokenType_name[45:47],
	8192:    _tokenType_name[47:49],
	16384:   _tokenType_name[49:51],
	32768:   _tokenType_name[51:53],
	65536:   _tokenType_name[53:56],
	131072:  _tokenType_name[56:58],
	262144:  _tokenType_name[58:64],
	524288:  _tokenType_name[64:70],
	1048576: _tokenType_name[70:77],
	2097152: _tokenType_name[77:80],
}

func (i tokenType) String() string {
	if str, ok := _tokenType_map[i]; ok {
		return str
	}
	return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
}
